#!/usr/bin/env bash
#redirect

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start nginx service
sudo service nginx start

# Allow nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up /redirect_me to a YouTube vid
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo -e "\nCompleted.\n"

