#!/usr/bin/env bash
# Script to ping an IP address

# Check if argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
