#!/usr/bin/env bash
# Function to handle signals
cleanup() {
    echo "Deleting PID file and terminating"
    rm -f /var/run/myscript.pid
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM

echo $$ > /var/run/myscript.pid

trap cleanup SIGQUIT SIGTERM

echo "To infinity and beyond"
while true; do
    sleep 1
done
