#!/usr/bin/env bash
# Function to handle signals
cleanup() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "Y U no love me?!"; exit 0' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM

echo $$ > /var/run/myscript.pid

trap cleanup SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 1
done
