#!/usr/bin/env bash
#manages process

PIDFILE="/var/run/my_process.pid"
SCRIPT="manage_my_process"

start() {
    if [ -f "$PIDFILE" ]; then
        echo "$SCRIPT is already running."
    else
        ./$SCRIPT &
        echo $! > "$PIDFILE"
        echo "$SCRIPT started"
    fi
}

stop() {
    if [ -f "$PIDFILE" ]; then
        kill $(cat "$PIDFILE")
        rm "$PIDFILE"
        echo "$SCRIPT stopped"
    else
        echo "$SCRIPT is not running."
    fi
}

restart() {
    stop
    start
    echo "$SCRIPT restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
