#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code, count occurrences, and sort the data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -rn
