#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code, count occurrences, and sort the data
awk '{ips[$1 " " $9]++} END {for (ip in ips) {print ips[ip] " " ip}}' \
| sort -rn | head -n 10
