#!/usr/bin/env bash
# Check if running in Docker
if grep -q docker /proc/1/cgroup; then
    echo "Running in Docker."
else
    echo "This script is intended to run inside a Docker container."
    exit 1
fi
