#!/usr/bin/env bash
# Script to display all active IPv4 IPs on the machine

# Use ifconfig to get information about network interfaces
# Filter out IPv4 addresses using grep and awk
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | sed 's/addr://'
