#!/usr/bin/env bash
#Run Nginx as Nginx
if ! command -v nginx &>/dev/null; then
	exit 1
fi
if ! id -u nginx &>/dev/null; then
	useradd -r -s /sbin/nologin nginx
fi

NGINX_CONF="/etc/nginx/nginc.conf"

if [ -f "$NGINX_CONF" ]; then
	sed -i 's/^user.*/user nginx;/' "$NGINX_CONF"
	sed -i 's/listen\s\+80;/listen 8080;/' "$NGINX_CONF"
else
	exit 1
fi
